LESSON := lesson01

BIN := ../../../bin/$(LESSON)/$(LESSON).exe

LESSON_BUILD_DIR := ../../../build/$(LESSON)
LESSON_SRC_DIR := ../../../src/$(LESSON)

LESSON_OBJ := \
	$(LESSON_BUILD_DIR)/$(LESSON).o

include ../Makefile.inc
